# This file is auto-generated from the current state of the database. Instead of editing this file, 
# please use the migrations feature of Active Record to incrementally modify your database, and
# then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your database schema. If you need
# to create the application database on another system, you should be using db:schema:load, not running
# all the migrations from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20190522020543) do

  create_table "XP_PROC", :primary_key => "view_name", :force => true do |t|
    t.text "param_list"
    t.text "xSQL"
    t.text "def_param"
    t.text "opt_param"
    t.text "comment"
  end

  add_index "XP_PROC", ["view_name"], :name => "sqlite_autoindex_XP_PROC_1", :unique => true

  create_table "accounts", :force => true do |t|
    t.integer "member_id"
    t.string  "username"
    t.string  "password"
    t.string  "role"
    t.boolean "is_accountant"
    t.string  "hash_key"
  end

  create_table "activities", :force => true do |t|
    t.string  "title"
    t.date    "begin_date"
    t.date    "end_date"
    t.string  "place"
    t.integer "people_count"
    t.string  "manager"
    t.string  "teachers"
    t.text    "students"
    t.text    "achievement"
    t.text    "criticism"
    t.integer "expect_people_count"
    t.text    "method_and_goal"
    t.boolean "is_achievement"
    t.string  "picture_folder_name"
    t.time    "begin_time"
    t.time    "end_time"
    t.text    "content"
    t.string  "cleaner"
  end

  create_table "asset_item_detail_catalogs", :force => true do |t|
    t.string   "name"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "order_num"
  end

  create_table "asset_item_details", :force => true do |t|
    t.integer  "asset_item_id"
    t.date     "accounting_date"
    t.string   "title"
    t.decimal  "change_amount"
    t.decimal  "balance"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "asset_item_detail_catalog_id"
    t.text     "note"
  end

  create_table "asset_items", :force => true do |t|
    t.integer  "asset_id"
    t.string   "title"
    t.string   "currency"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.text     "memo"
    t.decimal  "amount"
    t.integer  "asset_belongs_to_id"
    t.boolean  "is_emergency"
    t.boolean  "is_save_for_goal"
    t.integer  "ntd_amount"
    t.string   "loan_begin_date"
    t.decimal  "loan_interest_rate"
  end

  create_table "assets", :force => true do |t|
    t.string "title"
    t.string "code"
  end

  create_table "books", :force => true do |t|
    t.string  "name"
    t.string  "title"
    t.string  "filename"
    t.string  "bg_filename"
    t.text    "collect_for_me"
    t.text    "collect_for_ppt"
    t.boolean "is_default"
  end

  create_table "courses", :force => true do |t|
    t.integer  "status_id"
    t.string   "title"
    t.integer  "order_num"
    t.string   "url_link"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "points"
  end

  create_table "donations", :force => true do |t|
    t.integer  "member_id"
    t.integer  "catalog_id"
    t.date     "accounting_date"
    t.string   "title"
    t.decimal  "amount"
    t.text     "note"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "histories", :force => true do |t|
    t.integer "member_id"
    t.date    "class_date"
    t.string  "class_teacher"
    t.string  "class_title"
    t.text    "class_feel"
    t.string  "name"
    t.integer "score"
    t.boolean "is_passed"
    t.integer "points"
    t.string  "class_type"
    t.integer "area_id"
    t.boolean "is_public_class"
  end

  create_table "life_catalogs", :force => true do |t|
    t.string  "name"
    t.integer "order_num"
    t.decimal "weight"
    t.boolean "chartable"
    t.boolean "goalable"
    t.integer "total_minutes"
    t.integer "line_order_num"
    t.integer "goal_minutes"
  end

  create_table "life_goals", :force => true do |t|
    t.integer  "param_id"
    t.string   "title"
    t.integer  "minutes"
    t.string   "resource_url"
    t.boolean  "is_pass"
    t.date     "pass_date"
    t.integer  "order_num"
    t.integer  "completed_minutes"
    t.boolean  "is_todo"
    t.string   "begin_time"
    t.string   "end_time"
    t.boolean  "is_show"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "life_items", :force => true do |t|
    t.string   "name"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "life_catalog_id"
    t.integer  "total_minutes"
    t.boolean  "is_not_chart"
    t.boolean  "is_goal"
    t.integer  "goal_minutes"
    t.integer  "order_num"
    t.string   "begin_date"
    t.string   "end_date"
    t.text     "main_content"
    t.text     "main_goal"
    t.integer  "total_days"
    t.boolean  "is_finished"
  end

  create_table "life_records", :force => true do |t|
    t.integer  "life_item_id"
    t.string   "rec_date"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "used_minutes"
    t.text     "memo"
    t.boolean  "is_not_goal"
  end

  create_table "member_reports", :force => true do |t|
    t.integer  "area_id"
    t.date     "rec_date"
    t.integer  "family_count"
    t.integer  "student_member_count"
    t.integer  "worker_member_count"
    t.integer  "generation2_1_count"
    t.integer  "generation2_2_count"
    t.integer  "student_new_count"
    t.integer  "worker_new_count"
    t.integer  "blessedable_count"
    t.integer  "leader_count"
    t.integer  "staff_count"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "m_core_student"
    t.integer  "m_core_young"
    t.integer  "m_core_adult"
    t.integer  "m_new_student"
    t.integer  "m_new_young"
    t.integer  "m_new_adult"
    t.integer  "m_normal_student"
    t.integer  "m_normal_young"
    t.integer  "m_normal_adult"
    t.integer  "f_core_student"
    t.integer  "f_core_young"
    t.integer  "f_core_adult"
    t.integer  "f_new_student"
    t.integer  "f_new_young"
    t.integer  "f_new_adult"
    t.integer  "f_normal_student"
    t.integer  "f_normal_young"
    t.integer  "f_normal_adult"
    t.integer  "m_core_college"
    t.integer  "m_new_college"
    t.integer  "m_normal_college"
    t.integer  "f_core_college"
    t.integer  "f_new_college"
    t.integer  "f_normal_college"
    t.text     "m_core_student_ids"
    t.text     "m_core_young_ids"
    t.text     "m_core_adult_ids"
    t.text     "m_new_student_ids"
    t.text     "m_new_young_ids"
    t.text     "m_new_adult_ids"
    t.text     "m_normal_student_ids"
    t.text     "m_normal_young_ids"
    t.text     "m_normal_adult_ids"
    t.text     "f_core_student_ids"
    t.text     "f_core_young_ids"
    t.text     "f_core_adult_ids"
    t.text     "f_new_student_ids"
    t.text     "f_new_young_ids"
    t.text     "f_new_adult_ids"
    t.text     "f_normal_student_ids"
    t.text     "f_normal_young_ids"
    t.text     "f_normal_adult_ids"
    t.text     "m_core_college_ids"
    t.text     "m_new_college_ids"
    t.text     "m_normal_college_ids"
    t.text     "f_core_college_ids"
    t.text     "f_new_college_ids"
    t.text     "f_normal_college_ids"
    t.integer  "m_core_old"
    t.integer  "m_new_old"
    t.integer  "m_normal_old"
    t.integer  "m_registered_student"
    t.integer  "m_registered_young"
    t.integer  "m_registered_adult"
    t.integer  "m_registered_old"
    t.integer  "m_registered_college"
    t.integer  "m_inactive_student"
    t.integer  "m_inactive_young"
    t.integer  "m_inactive_adult"
    t.integer  "m_inactive_old"
    t.integer  "m_inactive_college"
    t.integer  "f_core_old"
    t.integer  "f_new_old"
    t.integer  "f_normal_old"
    t.integer  "f_registered_student"
    t.integer  "f_registered_young"
    t.integer  "f_registered_adult"
    t.integer  "f_registered_old"
    t.integer  "f_registered_college"
    t.integer  "f_inactive_student"
    t.integer  "f_inactive_young"
    t.integer  "f_inactive_adult"
    t.integer  "f_inactive_old"
    t.integer  "f_inactive_college"
    t.text     "m_core_old_ids"
    t.text     "m_new_old_ids"
    t.text     "m_normal_old_ids"
    t.text     "m_registered_student_ids"
    t.text     "m_registered_young_ids"
    t.text     "m_registered_adult_ids"
    t.text     "m_registered_old_ids"
    t.text     "m_registered_college_ids"
    t.text     "m_inactive_student_ids"
    t.text     "m_inactive_young_ids"
    t.text     "m_inactive_adult_ids"
    t.text     "m_inactive_old_ids"
    t.text     "m_inactive_college_ids"
    t.text     "f_core_old_ids"
    t.text     "f_new_old_ids"
    t.text     "f_normal_old_ids"
    t.text     "f_registered_student_ids"
    t.text     "f_registered_young_ids"
    t.text     "f_registered_adult_ids"
    t.text     "f_registered_old_ids"
    t.text     "f_registered_college_ids"
    t.text     "f_inactive_student_ids"
    t.text     "f_inactive_young_ids"
    t.text     "f_inactive_adult_ids"
    t.text     "f_inactive_old_ids"
    t.text     "f_inactive_college_ids"
    t.integer  "m_sunday_student"
    t.integer  "m_sunday_young"
    t.integer  "m_sunday_adult"
    t.integer  "m_sunday_old"
    t.integer  "m_sunday_college"
    t.text     "m_sunday_student_ids"
    t.text     "m_sunday_young_ids"
    t.text     "m_sunday_adult_ids"
    t.text     "m_sunday_old_ids"
    t.text     "m_sunday_college_ids"
    t.integer  "f_sunday_student"
    t.integer  "f_sunday_young"
    t.integer  "f_sunday_adult"
    t.integer  "f_sunday_old"
    t.integer  "f_sunday_college"
    t.text     "f_sunday_student_ids"
    t.text     "f_sunday_young_ids"
    t.text     "f_sunday_adult_ids"
    t.text     "f_sunday_old_ids"
    t.text     "f_sunday_college_ids"
    t.integer  "m_supporter_student"
    t.integer  "m_supporter_young"
    t.integer  "m_supporter_adult"
    t.integer  "m_supporter_old"
    t.integer  "m_supporter_college"
    t.text     "m_supporter_student_ids"
    t.text     "m_supporter_young_ids"
    t.text     "m_supporter_adult_ids"
    t.text     "m_supporter_old_ids"
    t.text     "m_supporter_college_ids"
    t.integer  "f_supporter_student"
    t.integer  "f_supporter_young"
    t.integer  "f_supporter_adult"
    t.integer  "f_supporter_old"
    t.integer  "f_supporter_college"
    t.text     "f_supporter_student_ids"
    t.text     "f_supporter_young_ids"
    t.text     "f_supporter_adult_ids"
    t.text     "f_supporter_old_ids"
    t.text     "f_supporter_college_ids"
    t.integer  "generation2_3_count"
  end

  create_table "members", :force => true do |t|
    t.string   "name"
    t.string   "sex"
    t.string   "mobile"
    t.date     "birthday"
    t.string   "email"
    t.string   "career"
    t.string   "picture"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "classification"
    t.boolean  "is_team_leader"
    t.boolean  "birthday_still_unknow"
    t.text     "memo"
    t.integer  "conductor_id"
    t.integer  "introducer_id"
    t.string   "school"
    t.boolean  "is_on_table"
    t.string   "interest"
    t.integer  "order_num"
    t.text     "pray_note"
    t.integer  "area_id"
    t.boolean  "is_core_leader"
    t.boolean  "is_staff"
    t.integer  "spouse_id"
    t.integer  "sex_id"
    t.boolean  "admin_only"
    t.boolean  "blessedable"
    t.boolean  "is_teacher"
    t.string   "educational_background"
    t.string   "occupation"
    t.integer  "blessing_number"
    t.integer  "father_id"
    t.boolean  "is_core_family"
    t.string   "english_name"
    t.boolean  "is_college"
    t.boolean  "is_2g"
    t.string   "spiritual_birthday"
    t.boolean  "is_manager"
    t.boolean  "is_cleaner"
  end

  create_table "param_changes", :force => true do |t|
    t.integer  "param_id"
    t.string   "title"
    t.decimal  "change_value"
    t.decimal  "value"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.date     "rec_date"
    t.boolean  "is_enjoy"
  end

  create_table "params", :force => true do |t|
    t.string   "name"
    t.string   "value"
    t.string   "title"
    t.text     "content"
    t.boolean  "rec_change"
    t.integer  "order_num"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "pay_logs", :force => true do |t|
    t.integer  "member_id"
    t.string   "title"
    t.decimal  "amount"
    t.boolean  "is_received"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "manager"
  end

  create_table "questions", :force => true do |t|
    t.string   "to_name"
    t.string   "title"
    t.string   "catalog"
    t.text     "description"
    t.text     "solution"
    t.boolean  "is_solved"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "member_id"
    t.boolean  "is_secret"
  end

  create_table "sim_characters", :force => true do |t|
    t.string   "name"
    t.integer  "sex"
    t.date     "birthday"
    t.string   "identity"
    t.integer  "intelligence_p"
    t.integer  "sprit_p"
    t.integer  "willpower_p"
    t.integer  "seek_truth_p"
    t.integer  "seek_love_p"
    t.integer  "seek_dream_p"
    t.integer  "express_p"
    t.integer  "coaching_p"
    t.integer  "leadership_p"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "will_comein_p"
    t.integer  "parent_id"
    t.string   "school_name"
    t.string   "school_major"
    t.integer  "educational_background_num"
    t.integer  "occupation_num"
    t.integer  "blessing_num"
    t.integer  "spouse_id"
    t.string   "photo"
    t.text     "log"
  end

  create_table "steps", :force => true do |t|
    t.string   "name"
    t.integer  "order_num"
    t.text     "memo"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "status_id"
  end

  create_table "traces", :force => true do |t|
    t.integer  "member_id"
    t.integer  "status_num"
    t.date     "last_class_date"
    t.string   "last_class_title"
    t.date     "next_class_date"
    t.string   "next_class_title"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "last_class_teacher"
    t.string   "next_class_teacher"
    t.text     "class_feel"
    t.boolean  "appointment_promise"
    t.string   "star_level"
    t.integer  "score"
    t.boolean  "is_passed"
    t.integer  "points"
    t.boolean  "appointment_made"
    t.text     "step_ids"
    t.string   "class_type"
    t.integer  "aid"
    t.boolean  "is_public_class"
    t.string   "place"
    t.time     "next_class_time"
    t.string   "next_class_content"
  end

end
